include /Makefile.qsta

flist = run.f
test = test_blvds_front_ctrl_ad_fixed_data_cal
top = demo_top dump_wave
verbosity = UVM_HIGH
vsim_args = -novopt -t ps +notimingchecks \
	-L xilinxcorelib_ver -L secureip -L unisims_ver -L unimacro_ver 

