/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_CIMPORTS
#define INCLUDED_CIMPORTS

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
CFunction(
    int mcd,
    int level,
    int i1);

DPI_LINK_DECL DPI_DLLESPEC
int
CTask(
    int mcd,
    int level,
    int i1,
    int i2,
    int* o1,
    int* o2,
    int* io1);

DPI_LINK_DECL int
SVFunction(
    int level,
    int i1);

DPI_LINK_DECL int
SVTask(
    int level,
    int i1,
    int i2,
    int* o1,
    int* o2,
    int* io1);

#endif 
